apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "gke-ingress.fullname" . }}
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 8080
    type: HTTP
    requestPath: /actuator/health
