apiVersion: v1
kind: Service
metadata:
  name: {{ include "gke-ingress.fullname" . }}
  labels:
    {{- include "gke-ingress.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "gke-ingress.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpTargetPort }}

